# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'desafio' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for desafio
  pod 'Moya', '~> 8.0'
  pod 'Moya-ModelMapper', '~> 4.1'
  pod 'PKHUD', '~> 4.2'
  pod 'Kingfisher', '~> 3.3'
  pod 'Fabric'
  pod 'Crashlytics'

  target 'desafioTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Quick', '~> 1.0'
    pod 'Nimble', '~> 6.0'
  end

  target 'desafioUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
